import pptxgen from "pptxgenjs";

/**
 * ============================================================================
 * POWERPOINT (PPTX) PRESENTATION ENGINE (`generatePpt.js`)
 * ============================================================================
 * Generates widescreen (16:9) .pptx decks featuring cover slides, card containers,
 * bullet dots, and custom palettes using PptxGenJS.
 * ============================================================================
 */

const COLORS = {
    primary: "2563EB",
    secondary: "0F172A",
    text: "334155",
    light: "F8FAFC",
    border: "E3E8F0",
    white: "FFFFFF",
    muted: "64748B"
};

// 1. Cover Slide Builder
const addCover = (ppt, data) => {
    const slide = ppt.addSlide();
    slide.background = { color: COLORS.primary };

    // Top Accent Bar
    slide.addShape(ppt.ShapeType.rect, {
        x: 0,
        y: 0,
        w: 13.33,
        h: 0.18,
        fill: { color: "60A5FA" },
        line: { color: "60A5FA" }
    });

    // Title
    slide.addText(data.title || "Presentation", {
        x: 0.7,
        y: 2.2,
        w: 11.93,
        h: 1.5,
        align: "center",
        color: COLORS.white,
        bold: true,
        fontSize: 36
    });

    // Subtitle
    if (data.subtitle) {
        slide.addText(data.subtitle, {
            x: 1,
            y: 3.8,
            w: 11.33,
            h: 0.8,
            align: "center",
            color: "DBEAFE",
            fontSize: 18
        });
    }

    // Footer
    slide.addText("Generated by NovaMind", {
        x: 0,
        y: 6.8,
        w: 13.33,
        h: 0.3,
        align: "center",
        color: "BFDBFE",
        fontSize: 12
    });
};

// 2. Content Slide with Styled Cards & Bullet Dots
const addContentSlide = (ppt, title, points, page, total) => {
    const slide = ppt.addSlide();
    slide.background = { color: COLORS.white };

    // Slide Header
    slide.addText(title || "Slide", {
        x: 0.6,
        y: 0.35,
        w: 12,
        h: 0.5,
        fontSize: 24,
        bold: true,
        color: COLORS.primary
    });

    // Divider Line
    slide.addShape(ppt.ShapeType.line, {
        x: 0.6,
        y: 0.95,
        w: 12.13,
        h: 0,
        line: { color: COLORS.border, width: 1.2 }
    });

    // Points (Up to 6 per slide)
    const visiblePoints = (points || []).slice(0, 6);
    visiblePoints.forEach((point, index) => {
        const y = 1.3 + index * 0.85;

        // Card Container
        slide.addShape(ppt.ShapeType.roundRect, {
            x: 0.6,
            y,
            w: 12.13,
            h: 0.7,
            fill: { color: index % 2 === 0 ? "F8FAFC" : "EFF6FF" },
            line: { color: COLORS.border },
            radius: 0.08
        });

        // Bullet Dot
        slide.addShape(ppt.ShapeType.ellipse, {
            x: 0.85,
            y: y + 0.26,
            w: 0.15,
            h: 0.15,
            fill: { color: COLORS.primary },
            line: { color: COLORS.primary }
        });

        // Point Text
        slide.addText(point, {
            x: 1.15,
            y: y + 0.1,
            w: 11.3,
            h: 0.5,
            fontSize: 15,
            color: COLORS.text,
            fit: "shrink"
        });
    });

    // Footer Page Number & Branding
    slide.addText("NovaMind", {
        x: 0.6,
        y: 6.9,
        w: 3,
        h: 0.3,
        color: COLORS.muted,
        fontSize: 10
    });

    slide.addText(`${page}/${total}`, {
        x: 10.73,
        y: 6.9,
        w: 2,
        h: 0.3,
        align: "right",
        color: COLORS.muted,
        fontSize: 10
    });
};

// 3. Thank You Slide
const addThankYouSlide = (ppt) => {
    const slide = ppt.addSlide();
    slide.background = { color: COLORS.secondary };

    slide.addText("Thank You!", {
        x: 0,
        y: 2.2,
        w: 13.33,
        h: 1,
        align: "center",
        color: COLORS.white,
        bold: true,
        fontSize: 34
    });

    slide.addText("Generated By NovaMind AI", {
        x: 0,
        y: 4.0,
        w: 13.33,
        h: 0.5,
        align: "center",
        color: "94A3B8",
        fontSize: 16
    });
};

/**
 * Main PowerPoint Generator Entry Point
 * @param {Object} data - Structured slides data
 */
export const generatePpt = async (data) => {
    const ppt = new pptxgen();
    ppt.layout = "LAYOUT_WIDE";
    ppt.author = "NovaMind";
    ppt.title = data.title || "Presentation";
    ppt.subject = data.title || "Presentation";
    ppt.company = "NovaMind";

    addCover(ppt, data);

    if (Array.isArray(data?.slides)) {
        data.slides.forEach((s, i) => {
            addContentSlide(
                ppt,
                s.title,
                s.points,
                i + 1,
                data.slides.length
            );
        });
    }

    addThankYouSlide(ppt);

    return ppt;
};