import PDFDocument from "pdfkit";

/**
 * ============================================================================
 * PDF GENERATION ENGINE (`generatePdf.js`)
 * ============================================================================
 * Uses PDFKit to stream-render structured document sections into an A4 PDF Buffer.
 * ============================================================================
 * @param {Object} data - Structured document data { title, subtitle, sections: [{ heading, points: [] }] }
 * @returns {Promise<Buffer>} - Compiled PDF buffer
 */
export const generatePdf = async (data) => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({
            size: "A4",
            margin: 50,
            info: {
                Author: "NovaMind",
                Title: data.title || "Generated PDF",
                Creator: "NovaMind",
            }
        });

        const chunks = [];
        doc.on("data", (chunk) => chunks.push(chunk));
        doc.on("end", () => resolve(Buffer.concat(chunks)));
        doc.on("error", (err) => reject(err));

        // 1. Document Title
        doc
            .fontSize(28)
            .text(data.title || "Document", {
                align: "center"
            })
            .fillColor("#111827");

        if (data.subtitle) {
            doc.moveDown(0.5);
            // 2. Document Subtitle
            doc
                .fontSize(18)
                .text(data.subtitle, {
                    align: "center"
                })
                .fillColor("#6B7280");
        }

        doc.moveDown(2);

        // 3. Render Content Sections
        data?.sections?.forEach((s) => {
            doc
                .fontSize(18)
                .text(s.heading || "Section")
                .fillColor("#111827");

            doc.moveDown(0.5);

            // Render bullet points
            s?.points?.forEach((p) => {
                doc
                    .fontSize(12)
                    .text("• " + p, {
                        lineGap: 4
                    })
                    .fillColor("#374151");
            });

            doc.moveDown(1);
        });

        // 4. Document Footer
        doc.moveDown(1);
        doc
            .fontSize(10)
            .text("Generated by NovaMind", {
                align: "center"
            })
            .fillColor("#9CA3AF");

        // Finalize document stream
        doc.end();
    });
};